export interface GoogleReview {
  id: string;
  author: string;
  profileUrl: string;
  reviewerMeta?: string;
  originalDateLabel?: string;
  text: string | null;
  rating: number | null;
  source: "Google";
  tags: string[];
  featured?: boolean;
}

export const GOOGLE_BUSINESS = {
  rating: 5.0, // Set if you want a fixed number like 5.0, or null to hide
  reviewCount: 34,
  reviewsUrl: "https://maps.app.goo.gl/gnzHsN1j5TwCY5816",
  writeReviewUrl: "https://maps.app.goo.gl/gnzHsN1j5TwCY5816",
};

export const REVIEWS: GoogleReview[] = [
  {
    id: "1",
    author: "Sai Krishna Vennu",
    profileUrl: "https://www.google.com/maps/contrib/108176946318199102762/reviews?hl=en-IN",
    reviewerMeta: "Local Guide · 1 review",
    originalDateLabel: "2 weeks ago",
    text: "I had an excellent experience at Natural Dental Clinic. I took my daughter for a dental issue and the Doctor handled her with exceptional care, patience and kindness. She has a wonderful way of making children feel comfortable, which made the entire experience stress-free.\nThe doctor is highly skilled, approachable and genuinely cares about her patients. The treatment was excellent and the charges were very reasonable.\nI highly recommend Natural Dental Clinic. If you're looking for a caring, trustworthy and experienced dentist, this is definitely the right place. Thank you Doctor for your outstanding care👍",
    rating: null,
    source: "Google",
    tags: ["Child-Friendly Care", "Patient Care", "Affordability", "Comfort"],
    featured: true,
  },
  {
    id: "2",
    author: "Ajit Vunna",
    profileUrl: "https://www.google.com/maps/contrib/111328874822989895727/reviews?hl=en-IN",
    reviewerMeta: "Local Guide · 56 reviews · 7 photos",
    originalDateLabel: "a year ago",
    text: "Affordable and all services available for Dental. Good Start up. All The Best….Owner and staff are very kind and helpful toward customers satisfaction and flexible services.\nKids will be treated with special attention. Overly must visit dental care.",
    rating: null,
    source: "Google",
    tags: ["Affordability", "Child-Friendly Care", "Staff", "Services"],
    featured: true,
  },
  {
    id: "3",
    author: "Reshma Egalapati",
    profileUrl: "https://www.google.com/maps/contrib/109123266015254230746/reviews?hl=en-IN",
    reviewerMeta: "Local Guide · 19 reviews · 7 photos",
    originalDateLabel: "2 years ago",
    text: "Very friendly and handled with really good care. Made sure that I'm comfortable through out the treatment. They also have all the latest equipments.",
    rating: null,
    source: "Google",
    tags: ["Comfort", "Friendly Care", "Latest Equipment"],
    featured: true,
  },
  {
    id: "4",
    author: "chenmila Deekshitha",
    profileUrl: "https://www.google.com/maps/contrib/110538067794399040986/reviews?hl=en-IN",
    reviewerMeta: "4 reviews",
    originalDateLabel: "2 years ago",
    text: "I had a severe dental problem and this clinic helped me with my tooth decay......Just go for it✅ It's comfortable you'll have no complaints/regrets for sure!👍🏻",
    rating: null,
    source: "Google",
    tags: ["Comfort", "Dental Care"],
  },
  {
    id: "5",
    author: "Rama Prakash",
    profileUrl: "https://www.google.com/maps/contrib/104459263546050527501/reviews?hl=en-IN",
    reviewerMeta: "Local Guide · 17 reviews · 2 photos",
    originalDateLabel: "2 years ago",
    text: "Awesome experience with the service, went for a root canal treatment and I am so happy with the doc and explained clearly about the issue.",
    rating: null,
    source: "Google",
    tags: ["Root Canal", "Clear Explanation", "Patient Experience"],
    featured: true,
  },
  {
    id: "6",
    author: "Prajakta Zod",
    profileUrl: "https://www.google.com/maps/contrib/105719039325483214541/reviews?hl=en-IN",
    reviewerMeta: "5 reviews · 2 photos",
    originalDateLabel: "2 years ago",
    text: "Very polite doctor, easy appointments and Great service with affordable price.. Must visit for happy teeth 😁",
    rating: null,
    source: "Google",
    tags: ["Affordability", "Appointments", "Friendly Care"],
  },
  {
    id: "7",
    author: "d",
    profileUrl: "https://www.google.com/maps/contrib/114822260779084497330/reviews?hl=en-IN",
    reviewerMeta: "Local Guide · 8 reviews · 1 photo",
    originalDateLabel: "2 years ago",
    text: "Super affordable and one of the best clinics in Hyderabad. Had my root canal done and is worth it.",
    rating: null,
    source: "Google",
    tags: ["Root Canal", "Affordability"],
  },
  {
    id: "8",
    author: "Kandi Srijani",
    profileUrl: "https://www.google.com/maps/contrib/115262944854462423369/reviews?hl=en-IN",
    reviewerMeta: "1 review",
    originalDateLabel: "2 years ago",
    text: "Avaliable to help you to get the dental care uh need full range of general cosmetic protocols to ensure safe dental care and the dental clinic is safe and secure 💯",
    rating: null,
    source: "Google",
    tags: ["Dental Care", "Safety"],
  },
  {
    id: "9",
    author: "Bhagya Chelimila",
    profileUrl: "https://www.google.com/maps/contrib/106319483993542455699/reviews?hl=en-IN",
    reviewerMeta: "1 review",
    originalDateLabel: "2 years ago",
    text: "Very comfortable environment and treatment was great....worth visiting 👍😊Thankyou Natural clinic",
    rating: null,
    source: "Google",
    tags: ["Clinical Ambience", "Comfort", "Treatment"],
  },
  {
    id: "10",
    author: "vamshi",
    profileUrl: "https://www.google.com/maps/contrib/109597060207966541196/reviews?hl=en-IN",
    reviewerMeta: "4 reviews",
    originalDateLabel: "2 years ago",
    text: "Just got treated and less painful I can say\n...Friendly doctor and treatment was for reasonable cost\nTotally worth it👍just go for it✅",
    rating: null,
    source: "Google",
    tags: ["Friendly Care", "Affordability", "Comfort"],
  },
  {
    id: "11",
    author: "Challa Jayendra",
    profileUrl: "https://www.google.com/maps/contrib/101443920241462410316/reviews?hl=en-IN",
    reviewerMeta: "3 reviews",
    originalDateLabel: "2 years ago",
    text: "Had a good experience and nice hospitality\nThe best Dental clinic in rc puram area.",
    rating: null,
    source: "Google",
    tags: ["Hospitality", "Patient Experience", "RC Puram"],
  },
  {
    id: "12",
    author: "Sruthi Kasimalla",
    profileUrl: "https://www.google.com/maps/contrib/106714633214912302024/reviews?hl=en-IN",
    reviewerMeta: "5 reviews · 1 photo",
    originalDateLabel: "2 years ago",
    text: "Best clinic . Your service and tha staff members are very good",
    rating: null,
    source: "Google",
    tags: ["Service", "Staff"],
  },
  {
    id: "13",
    author: "Gangadhar Rao",
    profileUrl: "https://www.google.com/maps/contrib/116141392722057563372/reviews?hl=en-IN",
    reviewerMeta: "4 reviews",
    originalDateLabel: "2 years ago",
    text: "Sufficient time is allowing to patients to complete understand their issue and very good elaboration has given for identified issue and it's solution.",
    rating: null,
    source: "Google",
    tags: ["Clear Explanation", "Patient Care", "Consultation"],
    featured: true,
  },
  {
    id: "14",
    author: "Revathi Kudipudi",
    profileUrl: "https://www.google.com/maps/contrib/113505086713709766124/reviews?hl=en-IN",
    reviewerMeta: "3 reviews",
    originalDateLabel: "2 years ago",
    text: "Highly recommend this hospital for all dental problems..well maintained and affordable prices",
    rating: null,
    source: "Google",
    tags: ["Affordability", "Cleanliness"],
  },
  {
    id: "15",
    author: "APARNA PATNALA",
    profileUrl: "https://www.google.com/maps/contrib/113062546889801608876/reviews?hl=en-IN",
    reviewerMeta: "1 review · 1 photo",
    originalDateLabel: "2 years ago",
    text: "Very good environment and The way they treats patients is very nice and the treatment is very good",
    rating: null,
    source: "Google",
    tags: ["Clinical Ambience", "Patient Care"],
  },
  {
    id: "16",
    author: "Akhila Durgam",
    profileUrl: "https://www.google.com/maps/contrib/112901023237500661989/reviews?hl=en-IN",
    reviewerMeta: "3 reviews",
    originalDateLabel: "2 years ago",
    text: "Very happy to visit this clinic..Good hospitality thanks for everything.",
    rating: null,
    source: "Google",
    tags: ["Hospitality", "Patient Experience"],
  },
  {
    id: "17",
    author: "Jayanth korrapati",
    profileUrl: "https://www.google.com/maps/contrib/112083481504038371829/reviews?hl=en-IN",
    reviewerMeta: "Local Guide · 5 reviews",
    originalDateLabel: "2 years ago",
    text: "Appreciate the clinic for its cleanliness, safety protocols, and professionalism, appreciate the skilled doctors and use of modern technology.",
    rating: null,
    source: "Google",
    tags: ["Cleanliness", "Safety", "Technology", "Professionalism"],
    featured: true,
  },
  {
    id: "18",
    author: "Sai Nikhil",
    profileUrl: "https://www.google.com/maps/contrib/116533582578004975511/reviews?hl=en-IN",
    reviewerMeta: "Local Guide · 5 reviews · 7 photos",
    originalDateLabel: "2 years ago",
    text: "Nice service, all equipments are available and pain is less after treatment",
    rating: null,
    source: "Google",
    tags: ["Latest Equipment", "Service", "Comfort"],
  },
  {
    id: "19",
    author: "Dhoni Mahendra",
    profileUrl: "https://www.google.com/maps/contrib/105301425787217080064/reviews?hl=en-IN",
    reviewerMeta: "Local Guide · 25 reviews · 16 photos",
    originalDateLabel: "a year ago",
    text: "Totally worth it\nTreated so well",
    rating: null,
    source: "Google",
    tags: ["Treatment", "Patient Experience"],
  },
  {
    id: "20",
    author: "Darga Likitha",
    profileUrl: "https://www.google.com/maps/contrib/105010022109719835381/reviews?hl=en-IN",
    reviewerMeta: "3 reviews",
    originalDateLabel: "2 years ago",
    text: "Good treatment in a cool clinical ambience",
    rating: null,
    source: "Google",
    tags: ["Clinical Ambience", "Treatment"],
  },
  {
    id: "21",
    author: "Keerthi Shinde",
    profileUrl: "https://www.google.com/maps/contrib/109738159206278164670/reviews?hl=en-IN",
    reviewerMeta: "1 review",
    originalDateLabel: "2 years ago",
    text: "Good treatment in a cool clinical ambience",
    rating: null,
    source: "Google",
    tags: ["Clinical Ambience", "Treatment"],
  },
  {
    id: "22",
    author: "Bharat Kumar Kinjarapu",
    profileUrl: "https://www.google.com/maps/contrib/115970143005986622734/reviews?hl=en-IN",
    reviewerMeta: "Local Guide · 69 reviews · 14 photos",
    originalDateLabel: "2 years ago",
    text: "Good.... really Natural",
    rating: null,
    source: "Google",
    tags: ["Patient Experience"],
  },
  {
    id: "23",
    author: "Ashwitha reddy",
    profileUrl: "https://www.google.com/maps/contrib/110160357710254517258/reviews?hl=en-IN",
    reviewerMeta: "3 reviews · 1 photo",
    originalDateLabel: "2 years ago",
    text: "Good must visit",
    rating: null,
    source: "Google",
    tags: ["Patient Experience"],
  },
  {
    id: "24",
    author: "Sherikar Akshitha",
    profileUrl: "https://www.google.com/maps/contrib/101813405135082066000/reviews?hl=en-IN",
    reviewerMeta: "1 review",
    originalDateLabel: "2 years ago",
    text: "Professional is cool",
    rating: null,
    source: "Google",
    tags: ["Professionalism"],
  },
  {
    id: "25",
    author: "Karthik Pandu",
    profileUrl: "https://www.google.com/maps/contrib/114864956181220244686/reviews?hl=en-IN",
    reviewerMeta: "1 review · 1 photo",
    originalDateLabel: "4 months ago",
    text: "Great service, explains everything, soo friendly..🤩",
    rating: null,
    source: "Google",
    tags: ["Friendly Care", "Clear Explanation", "Service"],
    featured: true,
  },
  {
    id: "26",
    author: "Mehraj Mehreen",
    profileUrl: "https://www.google.com/maps/contrib/107179740067464579552/reviews?hl=en-IN",
    originalDateLabel: "3 months ago",
    text: null,
    rating: null,
    source: "Google",
    tags: [],
  },
  {
    id: "27",
    author: "kothakapu madhavi",
    profileUrl: "https://www.google.com/maps/contrib/116622082323471759603/reviews?hl=en-IN",
    reviewerMeta: "3 reviews",
    originalDateLabel: "2 years ago",
    text: null,
    rating: null,
    source: "Google",
    tags: [],
  },
  {
    id: "28",
    author: "Darga Sudhakar",
    profileUrl: "https://www.google.com/maps/contrib/114999542177459613825/reviews?hl=en-IN",
    reviewerMeta: "1 review",
    originalDateLabel: "2 years ago",
    text: null,
    rating: null,
    source: "Google",
    tags: [],
  },
  {
    id: "29",
    author: "Arenelli Akshitha",
    profileUrl: "https://www.google.com/maps/contrib/108578661740193216840/reviews?hl=en-IN",
    reviewerMeta: "1 review",
    originalDateLabel: "2 years ago",
    text: null,
    rating: null,
    source: "Google",
    tags: [],
  },
  {
    id: "30",
    author: "Srilaya Midde",
    profileUrl: "https://www.google.com/maps/contrib/112619308920857492885/reviews?hl=en-IN",
    reviewerMeta: "1 review",
    originalDateLabel: "2 years ago",
    text: null,
    rating: null,
    source: "Google",
    tags: [],
  },
  {
    id: "31",
    author: "Bharadwaj Rayudu",
    profileUrl: "https://www.google.com/maps/contrib/101207845076138274824/reviews?hl=en-IN",
    reviewerMeta: "8 reviews",
    originalDateLabel: "2 years ago",
    text: null,
    rating: null,
    source: "Google",
    tags: [],
  },
  {
    id: "32",
    author: "Manisha Thatipamula",
    profileUrl: "https://www.google.com/maps/contrib/117488116782650388156/reviews?hl=en-IN",
    reviewerMeta: "1 review",
    originalDateLabel: "2 years ago",
    text: null,
    rating: null,
    source: "Google",
    tags: [],
  }
];

export const WRITTEN_REVIEWS = REVIEWS.filter(r => r.text !== null);
export const FEATURED_REVIEWS = WRITTEN_REVIEWS.filter(r => r.featured);
export const TOTAL_REVIEWS_COUNT = REVIEWS.length;
export const WRITTEN_REVIEWS_COUNT = WRITTEN_REVIEWS.length;
export const RATING_ONLY_REVIEWS_COUNT = REVIEWS.length - WRITTEN_REVIEWS.length;

export function getUniqueTags(): string[] {
  const tagSet = new Set<string>();
  WRITTEN_REVIEWS.forEach(r => r.tags.forEach(t => tagSet.add(t)));
  return Array.from(tagSet).sort();
}
