export interface Service {
  slug: string;
  title: string;
  shortTitle: string;
  icon: string;
  tagline: string;
  description: string;
  overview: string;
  symptoms: string[];
  benefits: string[];
  process: { step: string; description: string }[];
  faqs: { question: string; answer: string }[];
  image: string;
  category: string;
  localCta: string;
  relatedSlugs: string[];
}

export const SERVICES: Service[] = [
  {
    slug: "root-canal-treatment",
    title: "Root Canal Treatment",
    shortTitle: "Root Canal",
    icon: "Shield",
    tagline: "Save your tooth. Relieve your pain.",
    category: "Restorative",
    description: "Root canal treatment to help save an infected or damaged tooth and relieve severe toothache. Treatment is carried out under local anaesthesia at Natural Dental Clinic in Ramachandrapuram.",
    overview:
      "Root Canal Treatment (RCT) is a procedure that removes infected or damaged pulp from inside a tooth, cleans and seals the root canals, and helps preserve the natural tooth where clinically possible. At Natural Dental Clinic in Ramachandrapuram, we use modern techniques and local anaesthesia to help make the procedure as comfortable as possible. Treatment suitability is assessed individually based on your clinical condition.",
    symptoms: [
      "Severe toothache or throbbing pain",
      "Prolonged sensitivity to hot or cold",
      "Darkening or discolouration of the tooth",
      "Swelling or tenderness in nearby gums",
      "Persistent pimple on the gums",
      "Cracked or chipped tooth with pain",
    ],
    benefits: [
      "Helps preserve your natural tooth — avoids extraction where clinically possible",
      "Designed to remove infected tissue and relieve symptoms",
      "Restores chewing function where appropriate",
      "Helps prevent spread of infection to adjacent teeth",
      "Can provide long-term results with proper care",
      "Maintains natural smile and appearance",
    ],
    process: [
      { step: "Consultation & X-ray", description: "We assess the tooth with X-rays and explain the treatment plan clearly before proceeding." },
      { step: "Local Anaesthesia", description: "The area is numbed to ensure you are comfortable throughout the procedure." },
      { step: "Pulp Removal", description: "The infected or damaged pulp is carefully removed from the root canals." },
      { step: "Cleaning & Shaping", description: "Canals are cleaned, disinfected, and shaped in preparation for sealing." },
      { step: "Sealing & Crown", description: "Canals are sealed and a crown is typically placed to restore the tooth's strength and function." },
    ],
    faqs: [
      { question: "How do I know if I may need a root canal?", answer: "Common signs include persistent tooth pain, sensitivity to heat or cold that lingers, swelling near a tooth, or darkening of a tooth. A dental examination and X-ray are needed to confirm whether root canal treatment is appropriate." },
      { question: "Is root canal treatment painful?", answer: "With modern local anaesthesia, most patients find the procedure more comfortable than expected. Mild soreness after the appointment is normal and typically manageable with over-the-counter medication." },
      { question: "How long does root canal treatment take?", answer: "Most root canal procedures are completed in 1–2 visits, each lasting around 60–90 minutes, depending on the complexity of the case." },
      { question: "Will I need a crown after a root canal?", answer: "In most cases, yes. A crown helps protect and restore the treated tooth, especially if significant tooth structure has been lost to decay or damage." },
      { question: "What happens if an infected tooth is left untreated?", answer: "Untreated dental infections can worsen over time and may affect surrounding teeth and gum tissue. It is advisable to seek a clinical evaluation promptly if you are experiencing symptoms." },
    ],
    image: "/images/services/root-canal.jpg",
    localCta: "If you have persistent tooth pain or sensitivity in Ramachandrapuram, contact Natural Dental Clinic for a dental evaluation to understand your options.",
    relatedSlugs: ["crowns-bridges", "general-dentistry", "gum-treatment"],
  },
  {
    slug: "dental-implants",
    title: "Dental Implants",
    shortTitle: "Implants",
    icon: "Star",
    tagline: "Long-lasting teeth. Natural look. Confident smile.",
    category: "Restorative",
    description: "Dental implants designed to provide a stable tooth-replacement option that closely resembles the appearance and function of natural teeth. Suitability is assessed at Natural Dental Clinic in Ramachandrapuram.",
    overview:
      "Dental implants are titanium posts placed into the jawbone to act as artificial tooth roots. They can support crowns, bridges, or dentures, providing a stable tooth-replacement solution. At Natural Dental Clinic in Ramachandrapuram, implant suitability is assessed individually — including bone density, gum health, and general health — and treatment is planned based on each patient's clinical needs.",
    symptoms: [
      "Missing one or more teeth",
      "Ill-fitting dentures causing discomfort",
      "Difficulty chewing or speaking",
      "Bone loss due to missing teeth",
      "Adjacent teeth shifting into gaps",
      "Self-consciousness about missing teeth",
    ],
    benefits: [
      "Designed to closely resemble the appearance and function of natural teeth",
      "Can provide a long-term tooth replacement option with proper care",
      "May help prevent bone loss in the jaw",
      "Does not require alteration of adjacent healthy teeth",
      "Restores chewing ability and comfort",
      "Can improve confidence where tooth loss has been a concern",
    ],
    process: [
      { step: "Evaluation & Planning", description: "Thorough assessment including X-rays to determine bone density, gum health, and implant suitability." },
      { step: "Implant Placement", description: "The titanium implant is placed into the jawbone under local anaesthesia." },
      { step: "Healing Period", description: "The implant integrates with the bone (osseointegration) over several weeks to months." },
      { step: "Abutment Fitting", description: "A connector piece (abutment) is attached to the implant once healing is confirmed." },
      { step: "Crown Placement", description: "A custom-made crown is fixed to the abutment, completing your tooth replacement." },
    ],
    faqs: [
      { question: "Am I suitable for dental implants?", answer: "Suitability depends on individual factors including jawbone density, gum health, general health, and oral hygiene. Each patient is assessed individually with X-rays before any recommendation is made." },
      { question: "How long do implants last?", answer: "With proper oral hygiene and regular dental check-ups, implants can remain functional for many years. Individual outcomes vary depending on care and clinical factors." },
      { question: "Is the implant procedure painful?", answer: "The procedure is carried out under local anaesthesia. Some soreness after is normal and manageable with appropriate medication prescribed by the dentist." },
      { question: "How do I care for dental implants?", answer: "Maintain good oral hygiene — brush twice daily, clean between teeth carefully, and attend regular dental check-ups as recommended." },
    ],
    image: "/images/services/implants.jpg",
    localCta: "Visit Natural Dental Clinic in Ramachandrapuram to discuss tooth-replacement options and whether dental implants may be suitable for your clinical needs.",
    relatedSlugs: ["crowns-bridges", "gum-treatment", "general-dentistry"],
  },
  {
    slug: "teeth-whitening",
    title: "Teeth Whitening",
    shortTitle: "Whitening",
    icon: "Sparkles",
    tagline: "Brighter smile. Greater confidence.",
    category: "Cosmetic",
    description: "Professional teeth whitening supervised at Natural Dental Clinic in Ramachandrapuram, designed to lighten tooth colour and reduce visible staining.",
    overview:
      "Professional teeth whitening is a cosmetic treatment that lightens tooth colour by targeting stains and discolouration. At Natural Dental Clinic in Ramachandrapuram, whitening is carried out under supervision to help achieve noticeable results while monitoring your gum health and comfort throughout. Results and suitability vary by individual, and a consultation is required before treatment begins.",
    symptoms: [
      "Yellowing or staining from tea, coffee, or tobacco",
      "General dullness of teeth over time",
      "Discolouration from certain medications",
      "Staining from certain foods and drinks",
      "Self-consciousness about tooth colour",
      "Desire for a noticeably brighter smile",
    ],
    benefits: [
      "Visibly lighter, brighter smile",
      "Professionally supervised treatment",
      "Gum health is monitored throughout",
      "Results can be maintained with proper aftercare",
      "More controlled outcome compared to over-the-counter products",
      "Sensitivity-reducing formulas used where appropriate",
    ],
    process: [
      { step: "Consultation", description: "We assess the current tooth shade, review suitability, and discuss realistic expectations for your individual case." },
      { step: "Gum Protection", description: "A protective barrier is applied to your gums before whitening begins." },
      { step: "Whitening Application", description: "Professional-grade whitening gel is carefully applied to the teeth." },
      { step: "Activation", description: "The gel may be activated to improve effectiveness, depending on the technique used." },
      { step: "Review & Aftercare", description: "Results are reviewed and aftercare instructions provided to help maintain your outcome." },
    ],
    faqs: [
      { question: "Will teeth whitening suit me?", answer: "Whitening works best on natural teeth with surface staining. It may not be effective on crowns, veneers, or certain types of intrinsic staining. A consultation is needed to assess your individual suitability." },
      { question: "How white will my teeth get?", answer: "Results vary by individual depending on the type and degree of staining. Realistic expectations are discussed during your consultation." },
      { question: "Will whitening cause sensitivity?", answer: "Some temporary sensitivity is common and usually short-lived. Sensitivity-reducing formulas can be used, and we monitor your comfort throughout the process." },
      { question: "How long do results last?", answer: "Results can be maintained for several months to a year or more with proper aftercare, including limiting staining foods and drinks and following hygiene guidance." },
    ],
    image: "/images/services/whitening.jpg",
    localCta: "To find out whether teeth whitening may be suitable for you, contact Natural Dental Clinic in Ramachandrapuram to arrange a consultation.",
    relatedSlugs: ["general-dentistry", "crowns-bridges", "braces-orthodontics"],
  },
  {
    slug: "braces-orthodontics",
    title: "Braces & Orthodontics",
    shortTitle: "Braces",
    icon: "Smile",
    tagline: "Straighten your teeth. Improve your bite.",
    category: "Orthodontic",
    description: "Orthodontic treatment to address misaligned teeth and bite concerns, available for children, teenagers and adults at Natural Dental Clinic in Ramachandrapuram.",
    overview:
      "Orthodontic treatment corrects misaligned teeth and jaw relationships, improving both the appearance of your smile and the function of your bite. Natural Dental Clinic offers orthodontic consultations for children, teenagers, and adults in Ramachandrapuram. Straighter teeth are also generally easier to clean, which supports long-term oral health. Treatment planning is based on individual clinical assessment.",
    symptoms: [
      "Crooked or overcrowded teeth",
      "Gaps between teeth",
      "Overbite, underbite, or crossbite",
      "Difficulty cleaning between crowded teeth",
      "Jaw pain or discomfort related to bite",
      "Concerns about smile alignment",
    ],
    benefits: [
      "Improved alignment of teeth and smile",
      "Better bite function and reduced jaw strain",
      "Easier to clean teeth, supporting dental health",
      "Reduces risk of uneven wear on teeth",
      "Long-lasting results with proper retention",
      "Treatment available for children and adults",
    ],
    process: [
      { step: "Orthodontic Assessment", description: "Detailed examination of teeth, bite, and jaw alignment. X-rays and study models may be used." },
      { step: "Treatment Planning", description: "A personalised plan is designed based on your specific clinical needs and treatment goals." },
      { step: "Appliance Fitting", description: "Orthodontic appliances are custom-fitted to your teeth." },
      { step: "Regular Adjustments", description: "Scheduled appointments to monitor progress and make adjustments." },
      { step: "Retention Phase", description: "After active treatment, retainers help maintain the corrected tooth positions long-term." },
    ],
    faqs: [
      { question: "What age is appropriate for orthodontic treatment?", answer: "Early orthodontic assessment is recommended from around age 7 for certain developmental concerns. Comprehensive braces treatment typically begins at age 11–14, though adults benefit equally from orthodontic care." },
      { question: "How long does orthodontic treatment take?", answer: "Duration varies by individual case, typically ranging from 12 to 24 months. An estimate is provided after clinical assessment." },
      { question: "Are braces uncomfortable?", answer: "Some mild discomfort is normal after placement and adjustments. This usually settles within a few days and can be managed with over-the-counter pain relief." },
      { question: "Will I need a retainer after braces?", answer: "Yes. Retainers are essential to maintain the corrected positions after braces are removed. Full guidance on retainer care is provided." },
      { question: "Can adults get braces?", answer: "Absolutely. Orthodontic treatment is effective at any age. Adults frequently seek treatment for both functional and aesthetic reasons." },
    ],
    image: "/images/services/braces.jpg",
    localCta: "For an orthodontic consultation in Ramachandrapuram, contact Natural Dental Clinic to have your teeth and bite assessed by Dr. Vandana Vytla.",
    relatedSlugs: ["pediatric-dentistry", "general-dentistry", "crowns-bridges"],
  },
  {
    slug: "wisdom-tooth-removal",
    title: "Wisdom Tooth Removal",
    shortTitle: "Wisdom Tooth",
    icon: "Activity",
    tagline: "Safe extractions for lasting relief.",
    category: "Oral Surgery",
    description: "Wisdom tooth extraction to relieve pain, address impaction, and prevent complications. Carried out with care and clear aftercare guidance at Natural Dental Clinic, Ramachandrapuram.",
    overview:
      "Wisdom teeth (third molars) are the last teeth to emerge, typically in the late teens or early twenties. They frequently erupt incorrectly or become impacted, causing pain, swelling, crowding, or infection. When evaluation indicates removal is clinically necessary, Natural Dental Clinic in Ramachandrapuram performs extractions with a focus on patient comfort and a smooth, guided recovery.",
    symptoms: [
      "Pain or throbbing at the back of the mouth",
      "Swollen, tender, or bleeding gums around the wisdom tooth area",
      "Difficulty opening the mouth or chewing",
      "Persistent bad breath or unpleasant taste",
      "Jaw stiffness or visible swelling",
      "Crowding of adjacent teeth",
    ],
    benefits: [
      "Relief from pain and pressure caused by impaction",
      "Helps prevent infection from spreading",
      "Protects adjacent healthy teeth from damage",
      "Reduces risk of crowding other teeth",
      "Removes the risk of abscess or cyst associated with impacted teeth",
      "Supports long-term oral health",
    ],
    process: [
      { step: "Consultation & X-ray", description: "X-ray assessment to evaluate tooth position and plan the safest approach to extraction." },
      { step: "Anaesthesia", description: "Local anaesthesia is administered to keep you comfortable throughout the procedure." },
      { step: "Careful Extraction", description: "The tooth is gently loosened and removed with minimal impact on surrounding tissue." },
      { step: "Site Care", description: "The extraction socket is cleaned and dressed. Sutures may be placed if clinically needed." },
      { step: "Aftercare Guidance", description: "You receive clear aftercare instructions, prescribed medications if needed, and a follow-up plan." },
    ],
    faqs: [
      { question: "How do I know if my wisdom tooth needs to be removed?", answer: "Persistent pain at the back of the mouth, swelling, difficulty chewing, or repeated infections are common indicators. A dental examination and X-ray are needed to evaluate whether removal is appropriate." },
      { question: "Does wisdom tooth removal hurt?", answer: "The procedure is carried out under local anaesthesia so you should not feel pain during extraction. Mild soreness and swelling for a few days after is normal and managed with prescribed or recommended medication." },
      { question: "How long is the recovery after extraction?", answer: "Most patients recover well within 7–10 days. Following aftercare instructions carefully supports smooth healing." },
      { question: "Do all wisdom teeth need to be removed?", answer: "Not always. Removal is only recommended when the tooth is causing or is very likely to cause clinical problems. Each case is individually evaluated." },
      { question: "What warning signs require immediate dental assessment?", answer: "Significant swelling spreading to the jaw or neck, difficulty breathing or swallowing, or high fever following extraction require prompt dental or medical attention." },
    ],
    image: "/images/services/wisdom-tooth.jpg",
    localCta: "If you are experiencing wisdom tooth pain or swelling in Ramachandrapuram, contact Natural Dental Clinic for a dental evaluation and to discuss your options.",
    relatedSlugs: ["gum-treatment", "general-dentistry", "crowns-bridges"],
  },
  {
    slug: "pediatric-dentistry",
    title: "Children's Dental Care",
    shortTitle: "Children's Dental",
    icon: "Baby",
    tagline: "Gentle care for little smiles.",
    category: "Preventive",
    description: "Child-friendly dental care in a calm, reassuring environment at Natural Dental Clinic, Ramachandrapuram. Our approach focuses on comfort, prevention, and helping children build a positive relationship with dental visits.",
    overview:
      "Children's dental health forms the foundation of a lifetime of healthy smiles. At Natural Dental Clinic in Ramachandrapuram, we create a warm, gentle, and reassuring environment specifically for children. Patients and parents who have visited have often commented on the patient and child-friendly approach at the clinic. Our focus is on prevention, education, early detection of any concerns, and helping children feel at ease during every dental visit.",
    symptoms: [
      "First dental visit (recommended around age 1 or when the first tooth appears)",
      "Toothache or sensitivity in a child",
      "Visible decay, spots, or discolouration on milk teeth",
      "Difficulty eating due to dental discomfort",
      "Gum swelling or an abscess",
      "Habits such as thumb sucking or teeth grinding",
    ],
    benefits: [
      "Helps establish healthy dental habits from an early age",
      "Aimed at preventing cavities and tooth decay",
      "Calm, child-friendly environment to reduce dental anxiety",
      "Monitors development of both milk and permanent teeth",
      "Educational guidance for both child and parent",
      "Early detection of orthodontic or developmental concerns",
    ],
    process: [
      { step: "Child-Friendly Welcome", description: "We create a warm, welcoming atmosphere to help children feel relaxed and comfortable from the moment they arrive." },
      { step: "Gentle Examination", description: "A thorough yet gentle check of teeth, gums, and jaw development — explained in a way the child can understand." },
      { step: "Cleaning & Fluoride", description: "Professional cleaning and fluoride application to help protect young teeth from decay." },
      { step: "Education", description: "We help children understand why brushing and flossing matter, using demonstrations suited to their age." },
      { step: "Parent Guidance", description: "Clear advice for parents on diet, dental hygiene habits, and what to monitor at home between visits." },
    ],
    faqs: [
      { question: "When should my child first visit the dentist?", answer: "We recommend a first dental visit by age 1 or when the first tooth appears, whichever comes earlier. Early visits help identify any concerns and help the child become comfortable with dental care." },
      { question: "How often should children visit the dentist?", answer: "Every 6 months for routine check-ups and preventive care is the standard recommendation for most children." },
      { question: "Are milk teeth important if they fall out anyway?", answer: "Yes. Healthy milk teeth are important for eating, speaking clearly, and holding the correct space for permanent teeth to grow into. Early loss of milk teeth can affect how the permanent teeth develop." },
      { question: "My child is nervous about the dentist — how do you help?", answer: "We work at the child's own pace, explaining each step in a gentle way and giving them time to feel comfortable. Our patients' parents have frequently noted that their children felt at ease during visits." },
      { question: "When should children start brushing and how should I help?", answer: "Start cleaning your child's teeth as soon as the first tooth appears. Use a soft toothbrush and a small amount of age-appropriate fluoride toothpaste. Parental supervision of brushing is recommended until around age 7–8." },
    ],
    image: "/images/services/pediatric.jpg",
    localCta: "Parents looking for children's dental care in Ramachandrapuram can contact Natural Dental Clinic to arrange a consultation for their child.",
    relatedSlugs: ["general-dentistry", "braces-orthodontics", "gum-treatment"],
  },
  {
    slug: "gum-treatment",
    title: "Gum Treatment",
    shortTitle: "Gum Care",
    icon: "Heart",
    tagline: "Healthy gums. Strong foundation for your smile.",
    category: "Periodontal",
    description: "Gum disease assessment and treatment at Natural Dental Clinic, Ramachandrapuram, including scaling and deep cleaning to help restore gum health and protect your teeth.",
    overview:
      "Healthy gums are essential for a healthy smile. Gum disease (periodontal disease) is one of the most common causes of tooth loss in adults and is frequently linked to systemic health conditions. At Natural Dental Clinic in Ramachandrapuram, we assess gum health thoroughly and provide appropriate treatment including scaling, root planing, and ongoing maintenance to help manage gum disease at various stages.",
    symptoms: [
      "Bleeding gums when brushing or flossing",
      "Red, swollen, or tender gums",
      "Gums that appear to be pulling away from the teeth",
      "Persistent bad breath not resolved by brushing",
      "Loose or shifting teeth",
      "Sensitivity at the gum line",
    ],
    benefits: [
      "Addresses infection and inflammation in the gums",
      "Helps prevent further bone and tooth loss",
      "Reduces bleeding and gum sensitivity",
      "Significantly improves breath freshness",
      "Protects teeth and supporting structures long-term",
      "Non-surgical treatment options available for appropriate cases",
    ],
    process: [
      { step: "Gum Assessment", description: "Thorough examination of gum depth, bleeding points, and bone levels using clinical probing and X-rays." },
      { step: "Scaling & Root Planing", description: "Deep cleaning to remove tartar, plaque, and bacteria from above and below the gumline." },
      { step: "Targeted Therapy", description: "Focused treatment to promote healing of affected gum tissue." },
      { step: "Antimicrobial Support", description: "Antibiotics or antimicrobial rinses may be prescribed to support the healing process." },
      { step: "Maintenance Programme", description: "A personalised hygiene schedule is recommended to help keep gum disease controlled long-term." },
    ],
    faqs: [
      { question: "When should I be concerned about my gums?", answer: "Bleeding gums when brushing, persistent bad breath, swollen or red gums, or any teeth feeling looser than usual are signs that a dental evaluation is needed. Early gum disease is much easier to manage than advanced cases." },
      { question: "Is gum disease reversible?", answer: "Early gum disease (gingivitis) can be reversed with appropriate treatment and improved home hygiene. Advanced gum disease (periodontitis) can be stabilised and managed, but not fully reversed." },
      { question: "Is gum treatment painful?", answer: "Deep cleaning is typically done under local anaesthesia for comfort. Mild soreness after treatment is normal and usually short-lived." },
      { question: "Can gum disease affect my general health?", answer: "Research links gum disease to conditions including heart disease and diabetes. Managing gum disease supports not just oral health but overall wellbeing." },
      { question: "How many appointments will I need?", answer: "Typically 2–4 appointments depending on the severity, followed by regular maintenance visits to keep gum health stable." },
    ],
    image: "/images/services/gum-treatment.jpg",
    localCta: "If you notice bleeding gums, persistent bad breath, or gum sensitivity in Ramachandrapuram, contact Natural Dental Clinic for a gum health assessment.",
    relatedSlugs: ["general-dentistry", "root-canal-treatment", "dental-implants"],
  },
  {
    slug: "crowns-bridges",
    title: "Crowns & Bridges",
    shortTitle: "Crowns & Bridges",
    icon: "Crown",
    tagline: "Restore strength. Renew your smile.",
    category: "Restorative",
    description: "Dental crowns to protect damaged teeth and bridges to replace missing teeth, using natural-looking materials at Natural Dental Clinic in Ramachandrapuram.",
    overview:
      "Dental crowns cap and protect damaged, weakened, or root-treated teeth, restoring their strength, shape, and appearance. Dental bridges replace one or more missing teeth by using crowns on adjacent teeth as anchors. At Natural Dental Clinic in Ramachandrapuram, we use tooth-coloured materials designed to look natural and integrate well with your existing teeth.",
    symptoms: [
      "Severely decayed or structurally damaged tooth",
      "Cracked or broken tooth",
      "A tooth that has undergone root canal treatment",
      "Missing one or more teeth",
      "Worn-down teeth affecting appearance or function",
      "Cosmetically imperfect teeth requiring restoration",
    ],
    benefits: [
      "Restores strength and full function to a damaged tooth",
      "Protects weakened teeth from further damage or fracture",
      "Natural-looking, tooth-coloured materials",
      "Bridges fill gaps to support function and smile",
      "Helps prevent adjacent teeth from shifting into a gap",
      "Long-lasting with proper care and regular check-ups",
    ],
    process: [
      { step: "Consultation & Planning", description: "Assessment of the tooth, surrounding structure, and bite. Shade matching for a natural appearance." },
      { step: "Tooth Preparation", description: "The tooth is shaped to accommodate the crown under local anaesthesia for comfort." },
      { step: "Impressions", description: "Precise impressions are taken for the custom fabrication of your crown or bridge." },
      { step: "Temporary Crown", description: "A temporary crown is placed while your permanent restoration is being crafted." },
      { step: "Permanent Fitting", description: "The final crown or bridge is checked for fit, bite, and appearance before being permanently cemented." },
    ],
    faqs: [
      { question: "When is a crown recommended?", answer: "A crown is typically recommended when a tooth is too damaged or weakened for a standard filling, after root canal treatment, or to improve the structure of a cracked or significantly worn tooth." },
      { question: "How long do crowns last?", answer: "With good oral hygiene and regular dental check-ups, quality crowns can last 10 years or more. Individual outcomes depend on the material, care, and bite habits." },
      { question: "Will a crown look natural?", answer: "Yes. We use tooth-coloured porcelain or ceramic materials designed to blend with the shade and appearance of your natural teeth." },
      { question: "How do I care for a crown or bridge?", answer: "Brush twice daily, use floss or interdental brushes carefully around bridges, avoid very hard or sticky foods, and attend regular dental check-ups." },
    ],
    image: "/images/services/crowns-bridges.jpg",
    localCta: "For a consultation about crowns or bridges in Ramachandrapuram, contact Natural Dental Clinic to have your tooth assessed and your options explained clearly.",
    relatedSlugs: ["root-canal-treatment", "dental-implants", "general-dentistry"],
  },
  {
    slug: "general-dentistry",
    title: "General Dentistry",
    shortTitle: "General Dental",
    icon: "Microscope",
    tagline: "Preventive care for lifelong oral health.",
    category: "Preventive",
    description: "Routine dental check-ups, professional cleaning, fillings, and preventive care at Natural Dental Clinic in Ramachandrapuram — for patients of all ages.",
    overview:
      "Good oral health begins with regular preventive care. Natural Dental Clinic in Ramachandrapuram provides routine dental check-ups, professional cleaning, fillings, and early detection of dental concerns before they develop into larger problems. General dentistry visits also include personalised oral health advice to help you maintain healthy teeth and gums between appointments.",
    symptoms: [
      "Due for a routine dental check-up",
      "Tooth sensitivity or mild, intermittent pain",
      "Visible decay or dark spots on teeth",
      "Chipped or broken tooth",
      "Tartar build-up or persistent bad breath",
      "Gum irritation or light bleeding",
    ],
    benefits: [
      "Early detection helps prevent more complex and costly treatments later",
      "Professional cleaning removes tartar that brushing alone cannot address",
      "Maintains overall oral health and fresh breath",
      "Allows monitoring of any developing concerns",
      "Suitable for patients of all ages",
      "Personalised oral health advice at each visit",
    ],
    process: [
      { step: "Examination", description: "Thorough examination of teeth, gums, bite, and oral soft tissues." },
      { step: "X-rays", description: "Diagnostic X-rays where clinically needed to detect issues not visible during the clinical examination." },
      { step: "Professional Cleaning", description: "Removal of plaque, tartar, and surface stains with professional scaling." },
      { step: "Treatment", description: "Any necessary treatments such as fillings, extractions, or onward referrals are discussed and arranged." },
      { step: "Preventive Advice", description: "Personalised guidance on brushing, flossing, diet, and your recommended review interval." },
    ],
    faqs: [
      { question: "How often should I visit the dentist?", answer: "Every 6 months is the standard recommendation for most people. Some patients with ongoing concerns may benefit from more frequent reviews, which we discuss individually." },
      { question: "What happens during a routine check-up?", answer: "We examine your teeth and gums, take X-rays if clinically indicated, perform professional cleaning, and discuss any concerns or treatment needs with you." },
      { question: "Are fillings noticeable?", answer: "We use tooth-coloured composite resin materials designed to match your natural tooth colour closely, making modern fillings very discreet." },
      { question: "Is a check-up important even if I have no dental pain?", answer: "Yes. Many dental problems such as early decay and gum disease are painless in their early stages. Regular check-ups allow these to be caught and addressed before they become more significant." },
    ],
    image: "/images/services/general-dentistry.jpg",
    localCta: "Book a routine dental check-up at Natural Dental Clinic in Ramachandrapuram — for yourself or your family.",
    relatedSlugs: ["gum-treatment", "root-canal-treatment", "pediatric-dentistry"],
  },
];

export function getServiceBySlug(slug: string): Service | undefined {
  return SERVICES.find((s) => s.slug === slug);
}

export const SERVICE_CATEGORIES = [...new Set(SERVICES.map((s) => s.category))];
